# Copyright 2017 The OpenPitrix Authors. All rights reserved.
# Use of this source code is governed by a Apache license
# that can be found in the LICENSE file.
FROM openpitrix/caddy

COPY Caddyfile.local /etc/Caddyfile
COPY ./ /srv/openpitrix.github.io/

WORKDIR /srv/openpitrix.github.io/

ENTRYPOINT ["/usr/bin/caddy"]
CMD ["--conf", "/etc/Caddyfile", "--log", "stdout"]